create table catalog_returns
(
    cr_returned_date_sk      int,
    cr_returned_time_sk      int,
    cr_item_sk               int,
    cr_refunded_customer_sk  int,
    cr_refunded_cdemo_sk     int,
    cr_refunded_hdemo_sk     int,
    cr_refunded_addr_sk      int,
    cr_returning_customer_sk int,
    cr_returning_cdemo_sk    int,
    cr_returning_hdemo_sk    int,
    cr_returning_addr_sk     int,
    cr_call_center_sk        int,
    cr_catalog_page_sk       int,
    cr_ship_mode_sk          int,
    cr_warehouse_sk          int,
    cr_reason_sk             int,
    cr_order_number          int,
    cr_return_quantity       int,
    cr_return_amount         decimal,
    cr_return_tax            decimal,
    cr_return_amt_inc_tax    decimal,
    cr_fee                   decimal,
    cr_return_ship_cost      decimal,
    cr_refunded_cash         decimal,
    cr_reversed_charge       decimal,
    cr_store_credit          decimal,
    cr_net_loss              decimal,
    primary key (cr_item_sk, cr_order_number)
);

create table web_returns
(
    wr_returned_date_sk      int,
    wr_returned_time_sk      int,
    wr_item_sk               int,
    wr_refunded_customer_sk  int,
    wr_refunded_cdemo_sk     int,
    wr_refunded_hdemo_sk     int,
    wr_refunded_addr_sk      int,
    wr_returning_customer_sk int,
    wr_returning_cdemo_sk    int,
    wr_returning_hdemo_sk    int,
    wr_returning_addr_sk     int,
    wr_web_page_sk           int,
    wr_reason_sk             int,
    wr_order_number          int,
    wr_return_quantity       int,
    wr_return_amt            decimal,
    wr_return_tax            decimal,
    wr_return_amt_inc_tax    decimal,
    wr_fee                   decimal,
    wr_return_ship_cost      decimal,
    wr_refunded_cash         decimal,
    wr_reversed_charge       decimal,
    wr_account_credit        decimal,
    wr_net_loss              decimal,
    primary key (wr_item_sk, wr_order_number)
);

create table web_sales
(
    ws_sold_date_sk          int,
    ws_sold_time_sk          int,
    ws_ship_date_sk          int,
    ws_item_sk               int,
    ws_bill_customer_sk      int,
    ws_bill_cdemo_sk         int,
    ws_bill_hdemo_sk         int,
    ws_bill_addr_sk          int,
    ws_ship_customer_sk      int,
    ws_ship_cdemo_sk         int,
    ws_ship_hdemo_sk         int,
    ws_ship_addr_sk          int,
    ws_web_page_sk           int,
    ws_web_site_sk           int,
    ws_ship_mode_sk          int,
    ws_warehouse_sk          int,
    ws_promo_sk              int,
    ws_order_number          int,
    ws_quantity              int,
    ws_wholesale_cost        decimal,
    ws_list_price            decimal,
    ws_sales_price           decimal,
    ws_ext_discount_amt      decimal,
    ws_ext_sales_price       decimal,
    ws_ext_wholesale_cost    decimal,
    ws_ext_list_price        decimal,
    ws_ext_tax               decimal,
    ws_coupon_amt            decimal,
    ws_ext_ship_cost         decimal,
    ws_net_paid              decimal,
    ws_net_paid_inc_tax      decimal,
    ws_net_paid_inc_ship     decimal,
    ws_net_paid_inc_ship_tax decimal,
    ws_net_profit            decimal,
    primary key (ws_item_sk, ws_order_number)
);

create table catalog_sales
(
    cs_sold_date_sk          int,
    cs_sold_time_sk          int,
    cs_ship_date_sk          int,
    cs_bill_customer_sk      int,
    cs_bill_cdemo_sk         int,
    cs_bill_hdemo_sk         int,
    cs_bill_addr_sk          int,
    cs_ship_customer_sk      int,
    cs_ship_cdemo_sk         int,
    cs_ship_hdemo_sk         int,
    cs_ship_addr_sk          int,
    cs_call_center_sk        int,
    cs_catalog_page_sk       int,
    cs_ship_mode_sk          int,
    cs_warehouse_sk          int,
    cs_item_sk               int,
    cs_promo_sk              int,
    cs_order_number          int,
    cs_quantity              int,
    cs_wholesale_cost        decimal,
    cs_list_price            decimal,
    cs_sales_price           decimal,
    cs_ext_discount_amt      decimal,
    cs_ext_sales_price       decimal,
    cs_ext_wholesale_cost    decimal,
    cs_ext_list_price        decimal,
    cs_ext_tax               decimal,
    cs_coupon_amt            decimal,
    cs_ext_ship_cost         decimal,
    cs_net_paid              decimal,
    cs_net_paid_inc_tax      decimal,
    cs_net_paid_inc_ship     decimal,
    cs_net_paid_inc_ship_tax decimal,
    cs_net_profit            decimal,
    primary key (cs_item_sk, cs_order_number)
);

create table store_sales
(
    ss_sold_date_sk       int,
    ss_sold_time_sk       int,
    ss_item_sk            int,
    ss_customer_sk        int,
    ss_cdemo_sk           int,
    ss_hdemo_sk           int,
    ss_addr_sk            int,
    ss_store_sk           int,
    ss_promo_sk           int,
    ss_ticket_number      int,
    ss_quantity           int,
    ss_wholesale_cost     decimal,
    ss_list_price         decimal,
    ss_sales_price        decimal,
    ss_ext_discount_amt   decimal,
    ss_ext_sales_price    decimal,
    ss_ext_wholesale_cost decimal,
    ss_ext_list_price     decimal,
    ss_ext_tax            decimal,
    ss_coupon_amt         decimal,
    ss_net_paid           decimal,
    ss_net_paid_inc_tax   decimal,
    ss_net_profit         decimal,
    primary key (ss_item_sk, ss_ticket_number)
);

create table catalog_page
(
    cp_catalog_page_sk     int,
    cp_catalog_page_id     text,
    cp_start_date_sk       int,
    cp_end_date_sk         int,
    cp_department          text,
    cp_catalog_number      int,
    cp_catalog_page_number int,
    cp_description         text,
    cp_type                text,
    primary key (cp_catalog_page_sk)
);

create table web_page
(
    wp_web_page_sk      int,
    wp_web_page_id      text,
    wp_rec_start_date   date,
    wp_rec_end_date     date,
    wp_creation_date_sk int,
    wp_access_date_sk   int,
    wp_autogen_flag     text,
    wp_customer_sk      int,
    wp_url              text,
    wp_type             text,
    wp_char_count       int,
    wp_link_count       int,
    wp_image_count      int,
    wp_max_ad_count     int,
    primary key (wp_web_page_sk)
);

create table store_returns
(
    sr_returned_date_sk   int,
    sr_return_time_sk     int,
    sr_item_sk            int,
    sr_customer_sk        int,
    sr_cdemo_sk           int,
    sr_hdemo_sk           int,
    sr_addr_sk            int,
    sr_store_sk           int,
    sr_reason_sk          int,
    sr_ticket_number      int,
    sr_return_quantity    int,
    sr_return_amt         decimal,
    sr_return_tax         decimal,
    sr_return_amt_inc_tax decimal,
    sr_fee                decimal,
    sr_return_ship_cost   decimal,
    sr_refunded_cash      decimal,
    sr_reversed_charge    decimal,
    sr_store_credit       decimal,
    sr_net_loss           decimal,
    primary key (sr_item_sk, sr_ticket_number)
);
