services:
    redis:
        image: redis:7.2.5-alpine
        container_name: redis
        hostname: redis
        command: ["redis-server","/etc/redis/redis.conf"]
        volumes:
            - /path/to/redis/data:/data
            - /path/to/redis/redis.conf:/etc/redis/redis.conf
        ports:
            - 127.0.0.1:6379:6379
        #   - 10.0.0.4:6379:6379
